### ISSUE TITLE
Crash when generating world

### ISSUE THREAD

**Issue by Fukashiro-Yukari** [Nyphet/nightworld#2]
Every time generating world will crash instant.

`---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-12-02 22:29:12
Description: Exception in server tick loop

java.lang.RuntimeException: Mixin transformation of net.minecraft.world.PortalForcer failed
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base@17.0.3/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at MC//net.minecraft.server.world.ServerWorld.<init>(ServerWorld.java:234)
	at net.minecraft.server.MinecraftServer.createWorlds(MinecraftServer.java:357)
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:322)
	at MC//net.minecraft.server.integrated.IntegratedServer.setupServer(IntegratedServer.java:69)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at app//org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at app//org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at app//org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 11 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [nightworld.mixins.json:PortalForcerMixin from mod nightworld] from phase [DEFAULT] in config [nightworld.mixins.json] FAILED during APPLY
	at app//org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at app//org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at app//org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/PortalForcer::redirectFilter with priority 1000 cannot inject into net/minecraft/world/PortalForcer::getPortalRect(Lnet/minecraft/util/math/BlockPos;ZLnet/minecraft/world/border/WorldBorder;)Ljava/util/Optional; merged by me.jellysquid.mods.lithium.mixin.ai.poi.fast_portals.PortalForcerMixin with priority 1000 [PREINJECT Applicator Phase -> nightworld.mixins.json:PortalForcerMixin from mod nightworld -> Prepare Injections ->  -> redirect$ddp000$nightworld$redirectFilter(Ljava/util/stream/Stream;Ljava/util/function/Predicate;)Ljava/util/stream/Stream; -> Prepare]
	at app//org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at app//org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at app//org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at app//org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
	at app//org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at app//org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at app//org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at app//org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at app//org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at app//org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 14 more`

**Comment by Crystal-Spider** [comment]
It seems to be a compatibility issue with Lithium.  
I will look more into it, meanwhile as a temporary fix you can [disable Lithium Fast Portals optimization](https://github.com/CaffeineMC/lithium-fabric/blob/develop/lithium-mixin-config.md#mixinaipoifast_portals).

**Comment by Crystal-Spider** [comment]
Looking more into it, it really seems that disabling Lithium Fast Portals optimization is the only way to prevent crashes and allow compatibility.  
I updated the readme and the mod pages with this information, thank you for reporting!

**Comment by Poopooracoocoo** [comment]
Could you please disable Lithium's ai.poi.fast_portals mixin yourself? https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric-mod.json

**Comment by Crystal-Spider** [comment]
Thanks for pointing that out!

**Comment by Crystal-Spider** [comment]
Waiting for #5

**Comment by Crystal-Spider** [comment]
Fixed with [v2.0.0](https://github.com/crystal-nest/nightworld/releases?q=2.0.0).
