### ISSUE TITLE
Error When Launching With NeoForge

### ISSUE THREAD

**Issue by thosegamer** [Nyphet/nightworld#4]
### I have confirmed no other issue reports this bug

- [X] I have searched for existing issues

### I have confirmed the mod is installed on the proper side

- [X] I have installed the mod properly

### Current behavior

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-04-30 19:00:39
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.neoforged.neoforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[neoforge-20.4.233-universal.jar%23258!/:?] {re:classloading}
	at net.neoforged.neoforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:125) ~[neoforge-20.4.233-universal.jar%23258!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.buildInitialScreens(Minecraft.java:679) ~[client-1.20.4-20231207.154220-srg.jar%23257!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.onGameLoadFinished(Minecraft.java:652) ~[client-1.20.4-20231207.154220-srg.jar%23257!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.onResourceLoadFinished(Minecraft.java:647) ~[client-1.20.4-20231207.154220-srg.jar%23257!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$6(Minecraft.java:635) ~[client-1.20.4-20231207.154220-srg.jar%23257!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.ifElse(Util.java:425) ~[client-1.20.4-20231207.154220-srg.jar%23257!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$7(Minecraft.java:629) ~[client-1.20.4-20231207.154220-srg.jar%23257!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.neoforged.neoforge.client.loading.NeoForgeLoadingOverlay.render(NeoForgeLoadingOverlay.java:146) ~[neoforge-20.4.233-universal.jar%23258!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1128) ~[client-1.20.4-20231207.154220-srg.jar%23257!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:voidscape:overlay,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:voidscape:overlay,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1263) ~[client-1.20.4-20231207.154220-srg.jar%23257!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:818) ~[client-1.20.4-20231207.154220-srg.jar%23257!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:244) ~[neoforge-20.4.233.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-2.0.17.jar:2.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-2.0.17.jar:2.0] {}
	at net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-2.0.17.jar:2.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-2.0.17.jar:2.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:197) ~[securejarhandler-2.1.24.jar:?] {}
-- MOD nightworld --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/neoforged/neoforge/network/NetworkRegistry$ChannelBuilder
		at crystalspider.nightworld.NightworldLoader.<clinit>(NightworldLoader.java:31) ~[nightworld-1.20.4-1.0.0.0-neoforge.jar%23239!/:1.0.0.0] {re:mixin,re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:111) ~[loader-2.0.17.jar%2396!/:2.0] {}
		at net.neoforged.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:129) ~[loader-2.0.17.jar%2396!/:2.0] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/alexa/AppData/Roaming/.minecraft/mods/nightworld-1.20.4-1.0.0.0-neoforge.jar
	Failure message: Nightworld (nightworld) has failed to load correctly
		java.lang.NoClassDefFoundError: net/neoforged/neoforge/network/NetworkRegistry$ChannelBuilder
	Mod Version: 1.0.0.0
	Mod Issue URL: https://github.com/Nyphet/nightworld/issues
	Exception message: java.lang.ClassNotFoundException: net.neoforged.neoforge.network.NetworkRegistry$ChannelBuilder
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:197) ~[securejarhandler-2.1.24.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at crystalspider.nightworld.NightworldLoader.<clinit>(NightworldLoader.java:31) ~[nightworld-1.20.4-1.0.0.0-neoforge.jar%23239!/:1.0.0.0] {re:mixin,re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:111) ~[loader-2.0.17.jar%2396!/:2.0] {}
	at net.neoforged.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:129) ~[loader-2.0.17.jar%2396!/:2.0] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 305733040 bytes (291 MiB) / 838860800 bytes (800 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i5-13400F
	Identifier: Intel64 Family 6 Model 191 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 4060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2882
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3667
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 24939.17
	Virtual memory used (MB): 13819.21
	Swap memory total (MB): 8704.00
	Swap memory used (MB): 120.90
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		sponge-mixin-0.13.1+mixin.0.8.5.jar mixin PLUGINSERVICE 
		loader-2.0.17.jar slf4jfixer PLUGINSERVICE 
		loader-2.0.17.jar runtime_enum_extender PLUGINSERVICE 
		at-modlauncher-10.0.1.jar accesstransformer PLUGINSERVICE 
		loader-2.0.17.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar mixin-synthetic-package TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		javafml@2.0
		lowcodefml@2.0
		minecraft@2.0
	Mod List: 
		SmartBrainLib-neoforge-1.20.4-1.14.jar            |SmartBrainLib                 |smartbrainlib                 |1.14                |COMMON_SET|Manifest: NOSIGNATURE
		blue_skies-1.20.4-1.3.32.jar                      |Blue Skies                    |blue_skies                    |1.3.32              |COMMON_SET|Manifest: NOSIGNATURE
		deep_dark-2.1.0.5 - NeoForge 20.4.223.jar         |Deep Dark Dimension           |deep_dark                     |2.1.0.5             |COMMON_SET|Manifest: NOSIGNATURE
		MutantMonsters-v20.4.1-1.20.4-NeoForge.jar        |Mutant Monsters               |mutantmonsters                |20.4.1              |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-neoforge-1.20.4-4.4.4.jar                |GeckoLib 4                    |geckolib                      |4.4.4               |COMMON_SET|Manifest: NOSIGNATURE
		botarium-neoforge-1.20.4-3.2.2.jar                |Botarium                      |botarium                      |3.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		AoA3-1.20.4-3.7.7.jar                             |Advent Of Ascension           |aoa3                          |3.7.7               |COMMON_SET|Manifest: NOSIGNATURE
		nightworld-1.20.4-1.0.0.0-neoforge.jar            |Nightworld                    |nightworld                    |1.0.0.0             |ERROR     |Manifest: NOSIGNATURE
		aether-1.20.4-1.4.1-neoforge.jar                  |The Aether                    |aether                        |1.20.4-1.4.1-neoforg|COMMON_SET|Manifest: NOSIGNATURE
		waystones-neoforge-1.20.4-16.0.5.jar              |Waystones                     |waystones                     |16.0.5              |COMMON_SET|Manifest: NOSIGNATURE
		TslatEffectsLib-neoforge-1.20.4-1.8.5.jar         |Tslat Effects Lib (TEL)       |tslateffectslib               |1.8.5               |COMMON_SET|Manifest: NOSIGNATURE
		neoforge-20.4.233-universal.jar                   |NeoForge                      |neoforge                      |20.4.233            |COMMON_SET|Manifest: NOSIGNATURE
		1022_tsdpp-neoforge-1.20.4.jar                    |The Secret Doors              |tsdpp                         |1.0.2.2             |COMMON_SET|Manifest: NOSIGNATURE
		good_nights_sleep-1.20.4-1.3.1.jar                |Good Night's Sleep            |good_nights_sleep             |1.3.1               |COMMON_SET|Manifest: NOSIGNATURE
		guardvillagers-2.1.0-1.20.4.jar                   |Guard Villagers               |guardvillagers                |2.1.0-1.20.4        |COMMON_SET|Manifest: NOSIGNATURE
		balm-neoforge-1.20.4-9.0.7.jar                    |Balm                          |balm                          |9.0.7               |COMMON_SET|Manifest: NOSIGNATURE
		shadowlands-1.20.4-3.8.jar                        |Shadowlands                   |shadowlands                   |3.8                 |COMMON_SET|Manifest: NOSIGNATURE
		azurelib-neo-1.20.4-2.1.7.jar                     |AzureLib                      |azurelib                      |2.1.7               |COMMON_SET|Manifest: NOSIGNATURE
		twilightforest-1.20.4-4.4.2235-universal.jar      |The Twilight Forest           |twilightforest                |4.4.2235            |COMMON_SET|Manifest: NOSIGNATURE
		athena-neoforge-1.20.4-3.3.0.jar                  |Athena                        |athena                        |3.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		structure_gel-1.20.4-2.18.1.jar                   |Structure Gel API             |structure_gel                 |2.18.1              |COMMON_SET|Manifest: NOSIGNATURE
		client-1.20.4-20231207.154220-srg.jar             |Minecraft                     |minecraft                     |1.20.4              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		jitl-2.1.3.jar                                    |Journey Into the Light        |jitl                          |2.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		mining-dimension-neoforge-1.20.4-1.0.5.jar        |Mining World                  |mining_dimension              |1.20.4-1.0.5        |COMMON_SET|Manifest: NOSIGNATURE
		resourcefulconfig-neoforge-1.20.4-2.4.7.jar       |Resourcefulconfig             |resourcefulconfig             |2.4.7               |COMMON_SET|Manifest: NOSIGNATURE
		car-neoforge-1.20.4-1.0.16.jar                    |Ultimate Car Mod              |car                           |1.20.4-1.0.16       |COMMON_SET|Manifest: NOSIGNATURE
		dimdungeons-192-neoforge-1.20.4.jar               |Dimensional Dungeons          |dimdungeons                   |192                 |COMMON_SET|Manifest: NOSIGNATURE
		curios-neoforge-7.3.4+1.20.4.jar                  |Curios API                    |curios                        |7.3.4+1.20.4        |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.20.4-85-NEOFORGE.jar                  |Patchouli                     |patchouli                     |1.20.4-85-NEOFORGE  |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.20.4-7.54.jar                        |Collective                    |collective                    |7.54                |COMMON_SET|Manifest: NOSIGNATURE
		The Cat Dimension V.0.5.1 (1.20.4).jar            |The Cat Dimension             |the_cat_dimension             |0.5.1               |COMMON_SET|Manifest: NOSIGNATURE
		[1.20.4] SecurityCraft v1.9.8-beta2.jar           |SecurityCraft                 |securitycraft                 |1.9.8-beta2         |COMMON_SET|Manifest: NOSIGNATURE
		sit-1.20.2-1.3.4.jar                              |Sit                           |sit                           |1.3.4               |COMMON_SET|Manifest: NOSIGNATURE
		resourcefullib-neoforge-1.20.4-2.4.10.jar         |Resourceful Lib               |resourcefullib                |2.4.10              |COMMON_SET|Manifest: NOSIGNATURE
		cumulus_menus-1.20.4-1.0.1-neoforge.jar           |Cumulus                       |cumulus_menus                 |1.20.4-1.0.1-neoforg|COMMON_SET|Manifest: NOSIGNATURE
		architectury-11.1.17-neoforge.jar                 |Architectury                  |architectury                  |11.1.17             |COMMON_SET|Manifest: NOSIGNATURE
		cryingportals-1.20.4-2.7.jar                      |Crying Portals                |cryingportals                 |2.7                 |COMMON_SET|Manifest: NOSIGNATURE
		PuzzlesLib-v20.4.42-1.20.4-NeoForge.jar           |Puzzles Lib                   |puzzleslib                    |20.4.42             |COMMON_SET|Manifest: NOSIGNATURE
		Voidscape-1.20.4-1.7.388.jar                      |Voidscape                     |voidscape                     |1.20.4-1.7.388      |COMMON_SET|Manifest: NOSIGNATURE
		The_Undergarden-1.20.4-0.8.15.jar                 |The Undergarden               |undergarden                   |0.8.15              |COMMON_SET|Manifest: NOSIGNATURE
		nitrogen_internals-1.20.4-1.1.0-neoforge.jar      |Nitrogen                      |nitrogen_internals            |1.20.4-1.1.0-neoforg|COMMON_SET|Manifest: NOSIGNATURE
		the_bumblezone-7.4.5+1.20.4-neoforge.jar          |The Bumblezone                |the_bumblezone                |7.4.5+1.20.4-neoforg|COMMON_SET|Manifest: NOSIGNATURE
		polylib-2004.0.3-build.139-neoforge.jar           |PolyLib                       |polylib                       |2004.0.3-build.139  |COMMON_SET|Manifest: NOSIGNATURE
		shrink-2.0.0.40-neoforge.jar                      |Shrink                        |shrink                        |2.0.0.40            |COMMON_SET|Manifest: NOSIGNATURE
		gamemenumodoption-neoforge-mc1.20.2-2.3.0.jar     |Game Menu Mod Option          |gamemenumodoption             |2.3.0               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 9ecfe83d-eb98-4669-bb92-4e32d34a7570
	FML: 20.4
	NeoForge: net.neoforged:20.4.233

### Expected behavior

it's should work but it does not

### Minecraft version

1.20.4

### Mod loader version

NeoForge

### Mod version

1.0.0.0

### Other mods

Mod List: 
		SmartBrainLib-neoforge-1.20.4-1.14.jar            |SmartBrainLib                 |smartbrainlib                 |1.14                |COMMON_SET|Manifest: NOSIGNATURE
		blue_skies-1.20.4-1.3.32.jar                      |Blue Skies                    |blue_skies                    |1.3.32              |COMMON_SET|Manifest: NOSIGNATURE
		deep_dark-2.1.0.5 - NeoForge 20.4.223.jar         |Deep Dark Dimension           |deep_dark                     |2.1.0.5             |COMMON_SET|Manifest: NOSIGNATURE
		MutantMonsters-v20.4.1-1.20.4-NeoForge.jar        |Mutant Monsters               |mutantmonsters                |20.4.1              |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-neoforge-1.20.4-4.4.4.jar                |GeckoLib 4                    |geckolib                      |4.4.4               |COMMON_SET|Manifest: NOSIGNATURE
		botarium-neoforge-1.20.4-3.2.2.jar                |Botarium                      |botarium                      |3.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		AoA3-1.20.4-3.7.7.jar                             |Advent Of Ascension           |aoa3                          |3.7.7               |COMMON_SET|Manifest: NOSIGNATURE
		nightworld-1.20.4-1.0.0.0-neoforge.jar            |Nightworld                    |nightworld                    |1.0.0.0             |ERROR     |Manifest: NOSIGNATURE
		aether-1.20.4-1.4.1-neoforge.jar                  |The Aether                    |aether                        |1.20.4-1.4.1-neoforg|COMMON_SET|Manifest: NOSIGNATURE
		waystones-neoforge-1.20.4-16.0.5.jar              |Waystones                     |waystones                     |16.0.5              |COMMON_SET|Manifest: NOSIGNATURE
		TslatEffectsLib-neoforge-1.20.4-1.8.5.jar         |Tslat Effects Lib (TEL)       |tslateffectslib               |1.8.5               |COMMON_SET|Manifest: NOSIGNATURE
		neoforge-20.4.233-universal.jar                   |NeoForge                      |neoforge                      |20.4.233            |COMMON_SET|Manifest: NOSIGNATURE
		1022_tsdpp-neoforge-1.20.4.jar                    |The Secret Doors              |tsdpp                         |1.0.2.2             |COMMON_SET|Manifest: NOSIGNATURE
		good_nights_sleep-1.20.4-1.3.1.jar                |Good Night's Sleep            |good_nights_sleep             |1.3.1               |COMMON_SET|Manifest: NOSIGNATURE
		guardvillagers-2.1.0-1.20.4.jar                   |Guard Villagers               |guardvillagers                |2.1.0-1.20.4        |COMMON_SET|Manifest: NOSIGNATURE
		balm-neoforge-1.20.4-9.0.7.jar                    |Balm                          |balm                          |9.0.7               |COMMON_SET|Manifest: NOSIGNATURE
		shadowlands-1.20.4-3.8.jar                        |Shadowlands                   |shadowlands                   |3.8                 |COMMON_SET|Manifest: NOSIGNATURE
		azurelib-neo-1.20.4-2.1.7.jar                     |AzureLib                      |azurelib                      |2.1.7               |COMMON_SET|Manifest: NOSIGNATURE
		twilightforest-1.20.4-4.4.2235-universal.jar      |The Twilight Forest           |twilightforest                |4.4.2235            |COMMON_SET|Manifest: NOSIGNATURE
		athena-neoforge-1.20.4-3.3.0.jar                  |Athena                        |athena                        |3.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		structure_gel-1.20.4-2.18.1.jar                   |Structure Gel API             |structure_gel                 |2.18.1              |COMMON_SET|Manifest: NOSIGNATURE
		client-1.20.4-20231207.154220-srg.jar             |Minecraft                     |minecraft                     |1.20.4              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		jitl-2.1.3.jar                                    |Journey Into the Light        |jitl                          |2.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		mining-dimension-neoforge-1.20.4-1.0.5.jar        |Mining World                  |mining_dimension              |1.20.4-1.0.5        |COMMON_SET|Manifest: NOSIGNATURE
		resourcefulconfig-neoforge-1.20.4-2.4.7.jar       |Resourcefulconfig             |resourcefulconfig             |2.4.7               |COMMON_SET|Manifest: NOSIGNATURE
		car-neoforge-1.20.4-1.0.16.jar                    |Ultimate Car Mod              |car                           |1.20.4-1.0.16       |COMMON_SET|Manifest: NOSIGNATURE
		dimdungeons-192-neoforge-1.20.4.jar               |Dimensional Dungeons          |dimdungeons                   |192                 |COMMON_SET|Manifest: NOSIGNATURE
		curios-neoforge-7.3.4+1.20.4.jar                  |Curios API                    |curios                        |7.3.4+1.20.4        |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.20.4-85-NEOFORGE.jar                  |Patchouli                     |patchouli                     |1.20.4-85-NEOFORGE  |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.20.4-7.54.jar                        |Collective                    |collective                    |7.54                |COMMON_SET|Manifest: NOSIGNATURE
		The Cat Dimension V.0.5.1 (1.20.4).jar            |The Cat Dimension             |the_cat_dimension             |0.5.1               |COMMON_SET|Manifest: NOSIGNATURE
		[1.20.4] SecurityCraft v1.9.8-beta2.jar           |SecurityCraft                 |securitycraft                 |1.9.8-beta2         |COMMON_SET|Manifest: NOSIGNATURE
		sit-1.20.2-1.3.4.jar                              |Sit                           |sit                           |1.3.4               |COMMON_SET|Manifest: NOSIGNATURE
		resourcefullib-neoforge-1.20.4-2.4.10.jar         |Resourceful Lib               |resourcefullib                |2.4.10              |COMMON_SET|Manifest: NOSIGNATURE
		cumulus_menus-1.20.4-1.0.1-neoforge.jar           |Cumulus                       |cumulus_menus                 |1.20.4-1.0.1-neoforg|COMMON_SET|Manifest: NOSIGNATURE
		architectury-11.1.17-neoforge.jar                 |Architectury                  |architectury                  |11.1.17             |COMMON_SET|Manifest: NOSIGNATURE
		cryingportals-1.20.4-2.7.jar                      |Crying Portals                |cryingportals                 |2.7                 |COMMON_SET|Manifest: NOSIGNATURE
		PuzzlesLib-v20.4.42-1.20.4-NeoForge.jar           |Puzzles Lib                   |puzzleslib                    |20.4.42             |COMMON_SET|Manifest: NOSIGNATURE
		Voidscape-1.20.4-1.7.388.jar                      |Voidscape                     |voidscape                     |1.20.4-1.7.388      |COMMON_SET|Manifest: NOSIGNATURE
		The_Undergarden-1.20.4-0.8.15.jar                 |The Undergarden               |undergarden                   |0.8.15              |COMMON_SET|Manifest: NOSIGNATURE
		nitrogen_internals-1.20.4-1.1.0-neoforge.jar      |Nitrogen                      |nitrogen_internals            |1.20.4-1.1.0-neoforg|COMMON_SET|Manifest: NOSIGNATURE
		the_bumblezone-7.4.5+1.20.4-neoforge.jar          |The Bumblezone                |the_bumblezone                |7.4.5+1.20.4-neoforg|COMMON_SET|Manifest: NOSIGNATURE
		polylib-2004.0.3-build.139-neoforge.jar           |PolyLib                       |polylib                       |2004.0.3-build.139  |COMMON_SET|Manifest: NOSIGNATURE
		shrink-2.0.0.40-neoforge.jar                      |Shrink                        |shrink                        |2.0.0.40            |COMMON_SET|Manifest: NOSIGNATURE
		gamemenumodoption-neoforge-mc1.20.2-2.3.0.jar     |Game Menu Mod Option          |gamemenumodoption             |2.3.0               |COMMON_SET|Manifest: NOSIGNATURE

**Comment by Crystal-Spider** [comment]
Currently, you need to downgrade your NeoForge version. Not far in the future, a new 1.20.4 version will come out that fixes this.

**Comment by Crystal-Spider** [comment]
Waiting for #5

**Comment by Crystal-Spider** [comment]
Fixed with [v2.0.0](https://github.com/crystal-nest/nightworld/releases?q=2.0.0).
